name: Build and Push Frontend to DockerHub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_push_frontend:
    name: Build and Push Frontend Image
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et Push de l'image Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/student-frontend:latest
          build-args: |
            REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }} 